-- full description of table
SELECT CONCAT('Table ', TABLE_NAME, '     ', CREATE_TABLE)
FROM (
    SELECT TABLE_NAME, CONCAT('CREATE TABLE `', TABLE_NAME, '` (') AS CREATE_TABLE
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'hbtn_0c_0' AND TABLE_NAME = 'first_table'
) AS CREATE_TABLES;